### PR TITLE
Create main.yml

### PR DESCRIPTION
**Pull request by Karitta123**

### CODE REVIEW

**Review by Karitta123 — COMMENTED** [review]
Yes

**Review by Karitta123 — COMMENTED** [review]
Hi Lisa

**Review by Karitta123 — COMMENTED** [review]
Hi Lisa

**Review by Karitta123 — COMMENTED** [review]
Hi miss you Lisa

**Comment by Karitta123** [comment]
FPTMN65

**Comment by viccastro0916** [comment]
span class="views"><var>22.5K</var> views</span>
                        <div class="rating-container neutral">
                            <div class="main-sprite icon"></div>
                            <div class="value">86%</div>
                        </div>
                                                                                            
                    
                    <var class="added">1 month ago</var>
                </div>

                            </div>
                    </div>

    </li>

<li class="pcVideoListItem js-pop videoblock videoBox"
                    id="v278600851"
        data-video-id="278600851"
    data-video-vkey="ph5e28a943a32ef"
    data-id="278600851"
    data-segment="straight"
    data-entrycode="VidPg-premVid"
    tabindex="0"
>
    <div class="wrap">
                <div class="phimage"
                    >
                                        <div class="preloadLine"></div>
                                                            <a href="/view_video.php?viewkey=ph5e28a943a32ef" title="Russian young streamer showed not only the face "                        class="fade fadeUp videoPreviewBg linkVideoThumb js-linkVideoThumb img "
                        data-related-url="/video/ajax_related_video?vkey=ph5e28a943a32ef"
                                                >

**Pull request merged**
